# docker/docker-compose.yml (updated)
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./contracts.db
      - FAISS_INDEX_PATH=/app/faiss.index
    volumes:
      - ..:/app
    restart: "no"
